---
abstract: "Distributed ID generator (\"Yet another Unique ID\")"
author:
  - 'Six Apart,'
build_requires:
  ExtUtils::MakeMaker: 6.42
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.95'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Data-YUID
no_index:
  directory:
    - inc
    - t
requires:
  Danga::Socket: 0
  URI::Escape: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.04
